package slack

const (
	messageCommandNotRecognized = "Command not recognized."

	messageInvalidAction  = "Invalid action."
	messageSomethingWrong = "Something went wrong. Please, try again later or contact administrator."

	messageUserWithEmailNotFound      = "No user with email %s found in itechart exchange server. Check email spelling and try again."
	messageEmailIsAlreadyRegistered   = "Email %s is already registered in the booking bot."
	messageAuthIsFailed               = "Authentication attempt failed. Please check if you enter valid token, or enter /auth command again and follow its instructions."
	messageAuthIsFailedToken          = "Authentication attempt failed: you haven't got a token. Please, user /auth command and follow instructions."
	messageNeedToCompleteAuth         = "You need to complete your authentication by entering /auth command."
	messageNeedToCompleteAuthToken    = "You need to complete your authentication by entering authorisation token that was sent to your email here."
	messageAuthenticationIsSuccessful = "Authentication is successful. Please, choose your address by typing /address."
	messageAlreadyAuthenticated       = "You're already authenticated. You can start using bot by pressing buttons."
	messageHelloBot                   = "Hi, I'm a iTechArt bot, I can search information about free rooms."
	messageChooseDate                 = "Please, choose a date:"
	messageChooseRoomlist             = "Please, select your office address (roomlist):"
	messageAvailableRooms             = "Available rooms:"
	messageThereAreNoAvailableRooms   = "There are no available rooms at the chosen time."
	messageYouHaveChosen              = "You have chosen: "
	messageToday                      = "Today is: "
	messageStartTime                  = "Start time: "
	messageEndTime                    = "End time: "
	messageChooseTime                 = "Please, choose a time."
	messageChooseDuration             = "Please, choose duration."
	messageYouHaveNoMeetings          = "Currently you have no meetings that were planned with the help of this bot."
	messageWrongCalendarDay           = "Meetings cannot be created in the past and in the far future. Please, choose a different day."
	messageMeetingIsNotExist          = "Can`t find meeting, possibly it is already deleted."
	messageRoomlistIsChanged          = "Address successfully changed."
	messageRoomlistIsNotChosen        = "You haven't chosen address. Please, choose address by entering /address command."
	messageRoomlistIsSet              = "Address successfully set. Now you can start using bot by pressing buttons."
	messageRoomlistWasNotFound        = "The chosen address is not exist. Maybe you pressed an old button?\nTry again with /address."
	messageCantFindAvailableRoomNow   = "Sorry, there are no available free rooms now or in the near future."
	messageBotWasRestarted            = "Hello, it's me, TechArtBot. I was back 😎. I have been updated to version %s.\n%s"
	messageMeetingCreationCanceled    = "Meeting creation has been canceled."
	messageStartingMeetingCreation    = "Meeting creation has been started."
	messageReenterEmail               = "Bot has been restarted. Reenter you email with /auth for new token."
	messageEnterEmail                 = "Enter you outlook email or outlook login."
	messageDidNotChooseStartTime      = "You didn't choose meeting start time."
	messageDidNotChooseDuration       = "You didn't choose meeting duration."
	messageDidNotChooseRoom           = "You didn't choose meeting room."
	messageRoomFromWrongList          = "You chose room from wrong list. Please, choose room from actual list."
	messageDescriptionFast            = "/fast - view available rooms for today (choose time and duration)."
	messageDescriptionStart           = "/start - welcome the bot."
	messageDescriptionAuth            = "/auth - authentication."
	messageDescriptionAddress         = "/address - select your office location."
	messageDescriptionCustom          = "/custom - view available rooms (choose date, time, duration, location, subject)."
	messageDescriptionNow             = "/now - view available rooms now for 30 minutes (choose location)."
	messageDescriptionHelp            = "/help - show help message."
)
